FROM docker.io/westonsteimel/python:%%PLACEHOLDER%% as builder

ENV PYTHON_VERSION="%%PLACEHOLDER%%"
ENV PYTHON_PIP_VERSION="%%PLACEHOLDER%%"

ADD prepare-rootfs.sh /
RUN ./prepare-rootfs.sh

FROM docker.io/library/busybox:glibc

COPY --from=builder /build/rootfs/ /

USER python
WORKDIR /home/python

ENV PATH="/usr/local/bin:${PATH}" \
    LD_LIBRARY_PATH="/usr/local/lib/:${LD_LIBRARY_PATH}" \
    LANG="C.UTF-8"

CMD ["/usr/local/bin/python3"]
