FROM docker.io/westonsteimel/python:%%PLACEHOLDER%% as builder

ENV PYTHON_VERSION="%%PLACEHOLDER%%" 
ENV PYTHON_PIP_VERSION="%%PLACEHOLDER%%"

ADD prepare-rootfs.sh /
RUN ./prepare-rootfs.sh

FROM scratch

COPY --from=builder /build/rootfs/ /

ENV PATH="/usr/local/bin:${PATH}" \
    LD_LIBRARY_PATH="/usr/local/lib/:${LD_LIBRARY_PATH}"

CMD ["/usr/local/bin/python3"]
