on: 
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * SAT'
name: Build and publish
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
  QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
jobs:
  build_and_publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11', '3.12-rc']
        debian-version: ['buster', 'bullseye', 'bookworm', 'sid']
    steps:
      -
        name: Checkout
        uses: actions/checkout@main
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Build and Publish images
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
          DEBIAN_VERSION: ${{ matrix.debian-version }}
        run: |
          ./publish.sh
